apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    project: paran
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        name: elasticsearch
        ports:
        - containerPort: 9200
          name: elasticsearch
        env:
        - name: discovery.type
          value: single-node #멀티일 경우 multi-node
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 512Mi