apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    project: paran
spec:
  type: ClusterIP
  selector:    
    app: elasticsearch
  ports:
  - name: elasticsearch
    port: 9200
    targetPort: 9200