apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    project: paran 
spec:
  selector:
    app: kibana
  ports:
  - name: kibana
    port: 5601
    targetPort: 5601
  type: LoadBalancer